import type { Metadata } from "next";
import { Patua_One as FonsHs, Inter as FontSans } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { Header } from "./_components/Header";

const hs = FonsHs({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-hs",
});
const inter = FontSans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.variable,
          hs.variable,
          // biome-ignore lint/nursery/useSortedClasses: <explanation>
          "dark min-h-svh flex flex-col font-sans bg-gradient-to-r from-[hsl(246,55%,10%)] via-[hsl(243,40%,19%)] to-[hsl(240,27%, 19%)]",
        )}
      >
        <Header />
        <div className="flex flex-1 flex-col p-8">
          <TooltipProvider delayDuration={100}>{children}</TooltipProvider>
        </div>
        <footer className="border-t p-4">
          <div className="text-xs">
            All assets are trademark of ©2014 Blizzard Entertainment, Inc.
            <br /> All rights reserved. Heroes of Warcraft is a trademark, and
            Hearthstone is a registered trademark of Blizzard Entertainment,
            Inc. in the U.S. and/or other countries.
          </div>
        </footer>
      </body>
    </html>
  );
}
